Add user stories for payload scheduler
ODU-CGA-CubeSat/sealion-mission-architecture pull request #181
Opened 2022-01-12 00:47 UTC by BhagatjiJimesh

ODU and CGA Payload details
Closes #179

2022-02-02 02:23 UTC, capsulecorplab reviewed
TODO: add user story for (autonomous?) scheduled downlink

2022-02-09 02:42 UTC, capsulecorplab requested changes
Need to add user stories for scheduling:
- [ ] telemetry downlink
- [ ]  eventlog downlink

2022-02-09 02:42 UTC, capsulecorplab commented on architecture/2-UserStories/5-PayloadScheduler.yaml
> +- Ex2 Schedule data recording at specfic time interval (or orbital location) for ODU Payload?
I'm thinking the second example should be a separate user story all together; i.e., separate scheduling by time interval from scheduling by orbital location

2022-02-09 02:42 UTC, capsulecorplab commented on architecture/2-UserStories/5-PayloadScheduler.yaml
> +- Ex2 Schedule data recording at specfic time interval (or orbital location) for ODU Payload?
This also applies for `architecture/2-UserStories/5.1-ODUPayloadScheduler.yaml` and `architecture/2-UserStories/5.2-CGAPayloadScheduler.yaml`

2022-02-11 19:17 UTC, capsulecorplab commented
Need to determine
- how much time to allocate per scheduled task
- how far into the future do we want to be able to schedule a task

2022-02-11 20:04 UTC, capsulecorplab commented
dump health data info into eventlog per mission mode

2022-02-13 07:33 UTC, capsulecorplab requested changes
I would also remove `Ex1/Ex2` from the examples

2022-02-13 07:33 UTC, capsulecorplab commented on architecture/2-UserStories/5.1-ODUPayloadSchedulerTLE.yaml
> +- Ex1 Schedule data recording at 4min -10min (for a given orbital location) for ODU Payload
should remove this line

2022-02-13 07:33 UTC, capsulecorplab commented on architecture/2-UserStories/5.2-CGAPayloadSchedulerTLE.yaml
> +- Ex1 Schedule data recording at 4min -10min (for a given orbital location) for CGA Payload
should remove this line

2022-02-13 07:33 UTC, capsulecorplab commented on architecture/2-UserStories/6-PayloadSchedulerTimeInterval.yaml
> +id: 5.0
id s/b 6.0

2022-02-13 07:33 UTC, capsulecorplab commented on architecture/2-UserStories/6.1-ODUPayloadSchedulerTimeInterval.yaml
> +id: 5.1
id s/b 6.1

2022-02-13 07:33 UTC, capsulecorplab commented on architecture/2-UserStories/6.2-CGAPayloadSchedulerTimeInterval.yaml
> +id: 5.2
id s/b 6.2

2022-02-13 07:33 UTC, capsulecorplab commented on architecture/2-UserStories/6.3-DownlinkPayloadDataTimeInterval.yaml
> +id: 5.3
id s/b 6.3

2022-02-20 17:22 UTC, capsulecorplab requested changes
derivedFrom fields should point to their associated stakeholder needs

2022-02-23 00:32 UTC, capsulecorplab approved these changes
Will need to update examples with more concrete examples. Otherwise, LGTM

2022-02-23 00:33 UTC, merged

2022-02-23 00:33 UTC, kchiu002 approved these changes
LGTM